% plot energy landscape from lookup table generated by 
% COMSOL
addpath('./Matlab/');
file ="./library/fields/Assembly/quadrupole.txt";
set(0,'DefaultFigureWindowStyle','docked')
x = -100:0.25:100;
[xx,yy] = meshgrid(x,x);
kT = 1.38e-23 * 298;
epsilon = 80 * 8.85e-12;
a = 1.5e-6;
fcm = 0.4667;
pref = 2*pi*epsilon*a^3*fcm/kT;

%% read electric field file
data = load(file);
Ex = reshape(data(:,3),[length(x),length(x)]);
Ey = reshape(data(:,4),[length(x),length(x)]);
% Ez = reshape(data(:,12),[length(x),length(x)]);
% Fx = reshape(data(:,5),[length(x),length(x)]);
% Fy = reshape(data(:,6),[length(x),length(x)]);
% Fz = reshape(data(:,7),[length(x),length(x)]);
E = sqrt(Ex.^2 + Ey.^2);
E = E./(2e4);
% E = pref*(Ex.^2 + Ey.^2);
% Ez = pref * Ez.^2;
F = pref*(Fx.^2 + Fy.^2);
Fz = pref*Fz.^2;
[x_elec, y_elec] = meshgrid(-90:10:90);
x_elec = reshape(x_elec,[1,19^2]);
y_elec = reshape(y_elec,[1,19^2]);
% for i = 1:801
%     for j = 1:801
%         if (sqrt((i-401)^2 + (j-401)^2) > 60*4 || E(i,j) > 100)
% %         if abs(i-401) > 45*4 || abs(j-401) > 45*4|| E(i,j) > 100
% %         if (E(i,j) > 100)
%             E(i,j) = NaN;
%         end
%     end
% end
            
%% energy landscape in the unit of kT
figure(12)
clf
% colormap(flipud(gray))
% contourf(xx,yy,E, 100);
colormap((jet))
hold on 
% scatter(x_elec,y_elec, 100, 'y',...
%     'filled','s')
contourf(xx,yy, E',50,'linecolor','none');
% contourf(xx,yy, 0.5*E',[0:1:10, 10:5:100, 100:50:1000],'linecolor','none');
pbaspect([1 1 1])
axis([-90 90 -90 90])
xticks(-90:30:90)
yticks(-90:30:90)
axis on
box on
xlabel('x/ um')
ylabel('y/ um')
set(gca,'fontsize',14)
% [qx, qy] = meshgrid(-100:10:100);
% qEx = Ex(1:40:end,1:40:end);
% qEy = Ey(1:40:end,1:40:end);
% % qEx(8:13,5:10) = nan;
% % qEy(8:13,5:10) = nan;
% qEy = Ey(1:40:end,1:40:end);
% qExn = qEx./sqrt(qEx.^2+qEy.^2);
% qEyn = qEy./sqrt(qEx.^2+qEy.^2);
% hold on
% h = quiver(qy,qx,qExn,qEyn,'color','w','LineStyle','none','AutoScale','on',...
%     'AutoScaleFactor',1,'MaxHeadSize',0.1,'linewidth',2);
% h.Head.LineStyle = 'solid';  